# Generated by Django 3.2.5 on 2021-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=50, verbose_name='')),
                ('somme_depense', models.FloatField(verbose_name='')),
                ('date_depense', models.DateTimeField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Depense',
                'verbose_name_plural': 'Depenses',
            },
        ),
    ]
