# Generated by Django 2.2.24 on 2021-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
