# Generated by Django 2.2.24 on 2021-12-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211227_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Produit', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/images/', verbose_name='image'),
        ),
    ]
