# Generated by Django 4.0.4 on 2022-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211227_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset',
            field=models.ImageField(default='', upload_to='assets/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
