# Generated by Django 4.0.4 on 2022-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_assets_asset_alter_assets_id_alter_produit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
