# Generated by Django 4.0.4 on 2022-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_produit_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='urlImage'),
        ),
    ]
